import Header from "@/src/components/common/Header";
import "./globals.css";
import styles from "@/app/layout.module.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RecoilRootProvider from "@/src/providers/RecoilRootProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://t1.kakaocdn.net/kakao_js_sdk/2.4.0/kakao.min.js"
          integrity="sha384-mXVrIX2T/Kszp6Z0aEWaA8Nm7J6/ZeWXbL8UpGRjKwWe56Srd/iyNmWMBhcItAjH"
          crossOrigin="anonymous"
          defer
        ></script>
      </head>
      <body className={inter.className}>
        <RecoilRootProvider>
          <Header />
          <main className={styles.main}>{children}</main>
        </RecoilRootProvider>
      </body>
    </html>
  );
}
